Add admissions code
lorenzoworx/admissions-review pull request #1
Opened 2022-07-04 10:54 UTC by lorenzoworx

2022-07-04 11:03 UTC, lorenzoworx commented
- Setup linters on this project. For a guide on how to do that, check [here](https://github.com/microverseinc/linters-config).
- Make use of semantic HTML tags.
- Apply styles
- Add a descriptive readme

2022-07-04 11:06 UTC, sumairq requested changes
### Hi @lorenzoworx  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
🚨 🚨 🚨 
You have submitted a project, that does not meet requirement of having a code review by you on your pull request. You submitted a pull request without your review on it.  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-04 11:13 UTC, lorenzoworx commented
@sumairq Hey. I'm not quite sure I understand. I've left a comment on the pull request, what exactly makes this invalid?

2022-07-04 11:27 UTC, lorenzoworx reviewed
- Setup linters on this project. For a guide on how to do that, check [here](https://github.com/microverseinc/linters-config).
- Make use of semantic HTML tags.
- Apply styles
- Add a descriptive readme

2022-07-04 11:34 UTC, muneebulrehman requested changes
Hi @lorenzoworx , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- You have not used inline comments. Try to find a mistake in your code base and use inline comments for pointing out the same. Trust me, you will be using the inline comments all the time in the near future.
- Try to be more descriptive about the changes you are requesting. Like, if your want a specific code to be changed to semantic Html tags, point it out with inline comments.
- Your comments and review should not come as an order but as a suggestion. You can say 'Consider doing this' or 'How about doing like this'.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 11:43 UTC, lorenzoworx reviewed
- Setup linters on this project. For a guide on how to do that, check [here](https://github.com/microverseinc/linters-config).
- Add a descriptive readme

2022-07-04 11:43 UTC, lorenzoworx commented on index.html
> +    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
-Add script tags at the end of the HTML file

2022-07-04 11:43 UTC, lorenzoworx commented on index.html
> +      <select name="" id="dropdown">
- Don't leave attribute fields blank

2022-07-04 12:08 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @lorenzoworx 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Follow GitHub Flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions
- [ ] **I think it would be better to add a descriptive title of your Pull Request telling what changes are inside and also fill the Pull Request description field with a short summary describing introduced changes in more detail, as it is empty**

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 12:08 UTC, tresorsawasawa commented on index.html
> +    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
- [ ] Good job by making inline comments on your review. As mentioned by the previous reviewer,  think we can improve this comment review message by **being more polite as it sounds like an order**, **following it up with a "why" explaining** the importance of the changes that need to be made and **being more descriptive in your messages** 

Hints to follow:
> Good comment review message features: Statement of the aimed problem ❗, politely offer a suggestion 😏 and conclude with a reason or importance of making that change.

> You can use a phrase like this: **"I think it would be better to..."**

2022-07-04 12:08 UTC, tresorsawasawa commented on index.html
> +      <select name="" id="dropdown">
- [ ] Good job by making inline comments on your review. As mentioned by the previous reviewer,  think we can improve this comment review message by **being more polite as it sounds like an order**, **following it up with a "why" explaining** the importance of the changes that need to be made and **being more descriptive in your messages** 

Hints to follow:
> Good comment review message features: Statement of the aimed problem ❗, politely offer a suggestion 😏 and conclude with a reason or importance of making that change.

> You can use a phrase like this: **"I think it would be better to..."**

2022-07-04 12:22 UTC, lorenzoworx reviewed
- Setup linters on this project. For a guide on how to do that, check [here](https://github.com/microverseinc/linters-config).
- Add a descriptive readme as seen in the microverse readme template

2022-07-04 12:22 UTC, lorenzoworx commented on index.html
> +      <select name="" id="dropdown">
- I think it would be best not to leave attribute fields blank

2022-07-04 12:24 UTC, lorenzoworx reviewed
- Setup linters on this project. For a guide on how to do that, check [here](https://github.com/microverseinc/linters-config).
- Add a descriptive readme as seen in the microverse readme template

2022-07-04 12:24 UTC, lorenzoworx commented on index.html
> +    <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
-I think it would be better to add script tags at the end of the HTML file this ensures the parser isn't blocked until the very end

2022-07-04 12:29 UTC, KayLemba approved these changes
Hi @lorenzoworx  😃, 

You did a great job delivering such an amazing review 💯 Great summary 👍 Well done using the GitHub inline comments feature 👍 Polite and well-explained comments 👍

Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 12:29 UTC, merged

2022-12-05 12:43 UTC, Abenezer-Tilahun reviewed
Hi @lorenzoworx 😃,

You did a great job delivering such an amazing review 💯Your project is complete! There is nothing else to say other than... it's time to merge it
Congratulations! 🎉

## Highlights 👏🏻
✔️ Great summary 👍 
✔️ Well done using the GitHub inline comments feature 👍
✔️  Polite and well-explained comments 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._